[package]
name = "pbrt-v3-rs"
version = "0.1.0"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2021"

[dependencies]
api = { path = "../api" }
core = { path = "../core" }

env_logger = { workspace = true }
log = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }

dhat = { version = "0.2.4", optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.4.1", optional = true }

[features]
dhat-rs = ["dhat"]
jemalloc = ["tikv-jemallocator"]
