[workspace]

members = [
    "accelerators",
    "api",
    "cameras",
    "core",
    "filters",
    "integrators",
    "lights",
    "materials",
    "pbr-rust",
    "samplers",
    "shapes",
    "textures",
]