[package]
name = "pbr-rust"
version = "0.0.1"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2018"

[features]
sampled-spectrum = []

[dependencies]
byteorder = "1.3.4"
clap = "2.33.3"
either = "1.6.1"
env_logger = "0.8.2"
exr = "1.3.0"
float-cmp = "0.8.0"
hexf = "0.2.1"
image = "0.23.12"
itertools = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.14"
rand = "0.8.2"
rand_pcg = "0.3.0"
rayon = "1.5.0"
num_cpus = "1.13.0"
num-traits = "0.2.14"
ordered-float = "2.0.1"
order-stat = "0.1.3"
pest = "2.1.0"
pest_derive = "2.1.0"
regex = "1.4.3"
typed-arena = "2.0.1"

[dev-dependencies]
proptest = "0.10.0"
