[package]
name = "integrators"
version = "0.0.1"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2021"

[dependencies]
core = { path = "../core" }
samplers = { path = "../samplers" }

atom = "0.4.0"
crossbeam-channel = "0.5.6"
itertools = "0.10.3"
indicatif = "0.17.0"
log = "0.4.14"