[package]
name = "integrators"
version = "0.0.1"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2018"

[dependencies]

core = { path = "../core" }

itertools = "0.10.1"
log = "0.4.14"
rayon = "1.5.1"