[package]
name = "core"
version = "0.0.1"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2021"

[features]
#sampled-spectrum = []

[dependencies]
bitflags = "1.3.2"
byteorder = "1.3.4"
bumpalo = "3.8.0"
clap = { version = "3.0.7", features = ["derive"] }
either = "1.6.1"
exr = "1.3.0"
float-cmp = "0.9.0"
hexf = "0.2.1"
image = "0.23.14"
indicatif = { version = "0.16.2", features = ["rayon"] }
itertools = "0.10.1"
lazy_static = "1.4.0"
log = "0.4.14"
num_cpus = "1.13.0"
num-traits = "0.2.14"
ordered-float = "2.7.0"
pest = "2.1.3"
pest_derive = "2.1.0"
rayon = "1.5.1"
regex = "1.5.4"

[dev-dependencies]
proptest = "1.0.0"