[package]
name = "core"
version = "0.0.1"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2018"

[features]
#sampled-spectrum = []

[dependencies]
byteorder = "1.3.4"
clap = "2.33.3"
either = "1.6.1"
exr = "1.3.0"
float-cmp = "0.9.0"
hexf = "0.2.1"
image = "0.23.14"
itertools = "0.10.1"
lazy_static = "1.4.0"
log = "0.4.14"
rand = "0.8.4"
rand_pcg = "0.3.1"
num_cpus = "1.13.0"
num-traits = "0.2.14"
ordered-float = "2.7.0"
rayon = "1.5.1"
regex = "1.5.4"

[dev-dependencies]
proptest = "1.0.0"