[package]
name = "shapes"
version = "0.0.1"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2021"

[dependencies]
core = { path = "../core" }
textures = { path = "../textures" }

log = { workspace = true }
lazy_static = { workspace = true }
ply-rs = { workspace = true }
