[package]
name = "materials"
version = "0.0.1"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2018"

[dependencies]

core = { path = "../core" }
textures = { path = "../textures" }
either = "1.6.1"

lazy_static = "1.4.0"