[package]
name = "materials"
version = "0.0.1"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2021"

[dependencies]
core = { path = "../core" }
textures = { path = "../textures" }

lazy_static = "1.4.0"
log = "0.4.14"