[package]
name = "cameras"
version = "0.0.1"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2021"

[dependencies]
core = { path = "../core" }

crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
log = "0.4.14"