[package]
name = "cameras"
version = "0.0.1"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2018"

[dependencies]

core = { path = "../core" }

log = "0.4.14"
rayon = "1.5.1"
pest = "2.1.3"
pest_derive = "2.1.0"